name = Two Column Content
description = Two column layout for Atlas theme.
preview = preview.png
template = atlas-2-col-layout

; Regions
regions[header]         = Header
regions[preface]     = Preface
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/atlas-2-col/atlas-2-col.layout.css
