name = Three Column Content
description = Three column layout for Atlas theme.
preview = preview.png
template = atlas-3-col-layout

; Regions
regions[header]         = Header
regions[preface]     = Preface
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/atlas-3-col/atlas-3-col.layout.css
